### ISSUE TITLE
보스 블록 출력 오류(invalid matrix range)

### ISSUE THREAD

**Issue by caretop** [caretop/osscap2020#15]
` File "c:/Users/LG 14u530/Desktop/pytet_v0.2_led/realgam.py", line 537, in <module>
    Boss_tempBlk = iScreen.clip(Boss_top, Boss_left, Boss_top + BossBlk.get_dy(), Boss_left + BossBlk.get_dx())
  File "c:\Users\LG 14u530\Desktop\pytet_v0.2_led\matrix.py", line 78, in clip
    raise MatrixError("invalid matrix range")
matrix.MatrixError: invalid matrix range`

보스 등장시 다음 오류가 나옴 
boss_top을 변경하였을 때 임시적으로 해결되는 것으로 보아 블록 배열 범위 관련 문제인듯 함

**Comment by Sumin0916** [comment]
boss_top을 2로 변경했으
한번 더 테스트 해봐야 할듯
